running clients maybe working, a bunch of fixes for getting device and error checking

diff --git a/scripts/sim_net_conds b/scripts/sim_net_conds
--- a/scripts/sim_net_conds
+++ b/scripts/sim_net_conds
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # Script for simulating dynamic network conditions
-#
+# Probably works best if ran in the same directory as the script
 # TODO:
 #   - Limiting bandwidth
 #
@@ -9,7 +9,8 @@
 
 display_help () {
   printf "%b \n" "\033[1m"NAME"\033[0m"
-  printf "\t%s - Script to simulate network conditions of system on the edge\n" $(basename $0)
+  printf "\t%s - Script to simulate network conditions of system on the edge \n" $(basename $0)
+  printf "\t(probably works best if ran in the same directory as the script)"
   printf "\n%b \n" "\033[1m"SYNOPSIS"\033[0m"
   printf "\t%b %b %b %b %b\n" "\033[1m""$(basename $0) -N=""\033[0m""[\033[4m"ARGUMENT"\033[0m]" \
                          "\033[1m"" -n=""\"\033[0m""[\033[4m"ARGUMENT"\033[0m]\"" \
@@ -84,6 +85,21 @@ for i in "$@"; do
             TIMERETURN="${i#*=}"
             shift # Past argument=value
             ;;
+        ## Client executable 
+        -c=*|--client=*)
+            CLIENT="${i#*=}"
+            shift
+            ;;
+        ## The nodes in which to run the client executable
+        -s=*|--client_nodes=*)
+            CLIENTNODES="${i#*=}"
+            shift
+            ;;
+        ## (OPTIONAL) Argmuents to be passed to the client when it is ran
+        -a=*|--client_args=*)
+            CLIENTARGS="${i#*=}"
+            shift
+            ;;
         -h*|--help*)
           display_help
           exit 1
@@ -97,11 +113,25 @@ for i in "$@"; do
     esac
 done
 
-if [ "$NUMNODES" == "" ] || [ "$NODES" == "" ] || [ "$TIMEINTERVALS" == "" ] || [ "$LATENCYDELTA" == "" ] || [ "$TIMERETURN" == "" ] ; then
-  echo "Incorrect number of args!"
-  echo "Please provide all required arguments."
+auto_client=false
+
+if [ -n "$CLIENT" ] && [ -n "$CLIENTNODES" ] ; then
+  read -a client_nodes_arr <<< "$CLIENTNODES" 
+  client_name=$(basename ${CLIENT})
+  auto_client=true
+else
+  echo "Incorrect Arguments!"
+  echo "If you provide a client executable you must provide the nodes to run it on!"
   echo "See -h for usage."
+  exit 1
 fi
+
+#if [ "$NUMNODES" == "" ] || [ "$NODES" == "" ] || [ "$TIMEINTERVALS" == "" ] || [ "$LATENCYDELTA" == "" ] || [ "$TIMERETURN" == "" ] ; then
+#  echo "Incorrect number of args!"
+#  echo "Please provide all required arguments."
+#  echo "See -h for usage."
+#  exit 2
+#fi
 
 ## 5s
 TIMEINTERVAL=5
@@ -115,6 +145,8 @@ read -a nodes_arr <<< "$NODES"
 #echo $NUMNODES
 #for i in ${nodes_arr[@]} ; do echo $i; done
 #for i in $(seq 0 $(expr $NUMNODES - 1) ) ; do echo ${nodes_arr[$i]} ; done
+#for i in ${client_nodes_arr[@]} ; do echo $i; done
+#exit
 ## END DEBUG
 
 continue_delay () {
@@ -122,12 +154,24 @@ continue_delay () {
 }
 
 get_ip_and_device () {
+    ## Gets the ip of the node running the script so the node we want can use it to find its interface
+    my_ip=$(ifconfig | grep inet | awk 'FNR == 3 {print $2}')
     ## In awk FNR is the a variable that represents the number of records/lines to read
     ip=$(ping -c 1 $1 | awk 'FNR == 1 {print $3}' | sed -e 's/^.//' -e 's/.$//')
     ## Network interface is
-    dev=$(ip route get $ip | awk 'FNR == 1 {print $3}')
+    #dev=$(ip route get $my_ip | awk 'FNR == 1 {print $3}')
+    dev=$(ssh -T -o StrictHostKeyChecking=no $ip "ip route get $my_ip | awk 'FNR == 1 {print \$3}'")
 }
 
+## SCP the client to the client nodes
+if [ $auto_client ] ; then
+  for client_node in ${client_nodes_arr[@]} ; do
+    get_ip_and_device $client_node
+    scp $CLIENT $ip:
+  done
+fi
+
+exit
 ## Starts at 1 for multiplication reasons
 ## And because conceptually the first delay is the first interval
 currentinterval=1
@@ -165,6 +209,12 @@ do
     get_ip_and_device ${nodes_arr[$i]}
     ssh -T -o StrictHostKeyChecking=no $ip "sudo tc qdisc change dev $dev parent 1:2 handle 20: netem delay ${delay}ms"
   done
+  if [ $auto_client ] ; then
+    for client_node in ${client_nodes_arr[@]} ; do
+      get_ip_and_device $client_node
+      ssh -T -o StrictHostKeyChecking=no $ip "./$client_name $CLIENTARGS" 
+    done
+  fi
   ((currentinterval++))
 done
 
