updated help page

diff --git a/scripts/sim_net_conds b/scripts/sim_net_conds
--- a/scripts/sim_net_conds
+++ b/scripts/sim_net_conds
@@ -13,33 +13,36 @@ display_help () {
   printf "%b \n" "\033[1m"NAME"\033[0m"
   printf "\t%s - Script to simulate network conditions of system on the edge\n" $(basename $0)
   printf "\n%b \n" "\033[1m"SYNOPSIS"\033[0m"
-  printf "\t%b [%b]\n" "\033[1m""$(basename $0) -r""\033[0m" "\033[4m"ARGUMENT"\033[0m"
+  printf "\t%b %b %b %b\n" "\033[1m""$(basename $0) -n=""\033[0m""\"[\033[4m"ARGUMENT"\033[0m]\"" \
+                         "\033[1m"" -t=""\033[0m""[\033[4m"ARGUMENT"\033[0m]" \
+                         "\033[1m"" -l=""\033[0m""[\033[4m"ARGUMENT"\033[0m]" \
+                         "\033[1m"" -r=""\033[0m""[\033[4m"ARGUMENT"\033[0m]" 
   printf "\t%b \n" "\033[1m""$(basename $0) -h""\033[0m"
-  printf "\t%b [%b]\n" "\033[1m""$(basename $0) -d""\033[0m" "\033[4m"ARGUMENTS"\033[0m"
   printf "\n%b \n" "\033[1m"DESCRIPTION"\033[0m"
   printf "\t This script is used to simulate network conditions of systems on the edge. Such as: \n"
   printf "\t\t %b Adding a delay on a specific link between nodes that increases at some rate %b to simulate a node getting further away\n" "\033[1m""-""\033[0m" "\033[1m""r""\033[0m"
   printf "\t\t %b Decreasing bandwidth to simulate constrained network conditions on the edge\n" "\033[1m""-""\033[0m"
   printf "\t\t %b Simulating a node leaving and re-joining the cluster at varying speeds\n" "\033[1m""-""\033[0m"
   printf "\n"
-  printf "\t %b [%b], \n\t\tReset the network conditions of node %b back to normal \n\n" "\033[1m""-r""\033[0m" "\033[4m"IP"\033[0m" "\033[1m"IP"\033[0m"
+  printf "\t %b, %b \n\t\t List of node %b to add a delay onto. multiple node %b need to be quoted \n\n" "\033[1m""-n=""\033[0m""\"\033[4m"IPs"\033[0m\"" \
+                                                                                                         "\033[1m""--nodes=""\033[0m""\"\033[4m"IPs"\033[0m\""  \
+                                                                                                         "\033[1m"IPs"\033[0m" \
+                                                                                                         "\033[1m"IPs"\033[0m"
+  printf "\t %b, %b \n\t\t Integer value of how many intervals of 5s that a delay should be added \n\n" "\033[1m""-t=""\033[0m""\033[4m"NUM_INTERVALS"\033[0m" "\033[1m""--time_intervals=""\033[0m""\033[4m"NUM_INTERVALS"\033[0m"
+  printf "\t %b, %b \n\t\t Float value of how much delay should increase per time interval. \n\t\t All added delays are automatically removed after the specifed number of time intervals \n\n" "\033[1m""-l=""\033[0m""\033[4m"LATENCY_DELTA"\033[0m" "\033[1m""--latency_delta=""\033[0m""\033[4m"LATENCY_DELTA"\033[0m"
+  printf "\t %b, %b \n\t\t Integer value of after %b time intervals the delay should start to decrease. \n\t\t The return will evenly decrease the delay across the remaining time intervals specified in %b \n\n" "\033[1m""-r=""\033[0m""\033[4m"INTERVAL_RETURN"\033[0m"  \
+                                                                                                             "\033[1m""--time_return=""\033[0m""\033[4m"INTERVAL_RETURN"\033[0m" \ "\033[0m""\033[4m"INTERVAL_RETURN"\033[0m" \
+                                                                                                             "\033[0m""\033[1m"-t"\033[0m"
   printf "\t %b,\tDisplay this help message again \n\n" "\033[1m""-h""\033[0m"
-  printf "\t %b [%b] [%b] [%b],\n\t\tAdd a delay to a node up to a given max delay and with a given rate of increase per second\n" "\033[1m""-d""\033[0m" "\033[4m"IP"\033[0m" "\033[4m""MAX DELAY""\033[0m" "\033[4m"RATE"\033[0m"
-  printf "\t\tInitial delay starts at 0.1ms\n"
   printf "\n%b \n" "\033[1m"EXAMPLES"\033[0m"
   printf "\t%b\n" "\033[1m""Adding delay to a node:""\033[0m"
-  printf "\t\t./sim_net_conds -d node1 5.0 0.1\n\n"
-  printf "\t%b\n" "\033[1m""Removing delay from a node:""\033[0m"
-  printf "\t\t./sim_net_conds -r node1\n\n"
+  printf "\t\t./sim_net_conds -n=node1 -t=15 -l=0.1 -r=10\n\n"
+  printf "\t\t./sim_net_conds --nodes=node1 --time_intervals=15 --latency_delta=0.1 --time_return=10\n\n"
+  printf "\t\t./sim_net_conds -n=\"node1 node2 node3\" -t=15 -l=0.1 -r=10\n\n"
   printf "\t%b\n" "\033[1m""Displaying this help message again:""\033[0m"
   printf "\t\t./sim_net_conds -h\n\n"
 }
 
-if (( $# < 4 )); then
-  echo "Invalid Number of Arguments."
-  echo "Use '-h' to display help."
-  exit
-fi
 
 for i in "$@"; do
     case $i in
@@ -63,6 +66,10 @@ for i in "$@"; do
             TIMERETURN="${i#*=}"
             shift # Past argument=value
             ;;
+        -h*|--help*)
+          display_help
+          exit 1
+          ;;
         -*|--*)
             echo "Unknown option $i"
             exit 1
@@ -72,6 +79,11 @@ for i in "$@"; do
     esac
 done
 
+if (( $# < 4 )); then
+  echo "Invalid Number of Arguments."
+  echo "Use '-h' to display help."
+  exit
+fi
 
 ## 5s
 TIMEINTERVAL=5
@@ -103,7 +115,7 @@ ssh -T -o StrictHostKeyChecking=no $ip "sudo tc qdisc add dev $dev root netem de
 ((currentinterval++))
 while continue_delay
 do
-  sleep 1
+  sleep $TIMEINTERVAL
   if [ $currentinterval -ge $TIMERETURN ] ; then
     ## Progressively backing off delay
     ## `RI - [ (RI / (TI - RI)) * (CI - RI) ]` Should give a progressive decrease in delay between RI and TI and will end with a delay of 0
