added different args

diff --git a/scripts/sim_net_conds b/scripts/sim_net_conds
--- a/scripts/sim_net_conds
+++ b/scripts/sim_net_conds
@@ -1,9 +1,9 @@
 #!/bin/bash
 #
-# Script for simulating dynamic network conditions 
+# Script for simulating dynamic network conditions
 #
 # TODO:
-#   - Adding delay for multiple nodes at once 
+#   - Adding delay for multiple nodes at once
 #   - Limiting bandwidth
 #   - Adding '--arg=' syntax to arguments
 #
@@ -17,7 +17,7 @@ display_help () {
   printf "\t%b \n" "\033[1m""$(basename $0) -h""\033[0m"
   printf "\t%b [%b]\n" "\033[1m""$(basename $0) -d""\033[0m" "\033[4m"ARGUMENTS"\033[0m"
   printf "\n%b \n" "\033[1m"DESCRIPTION"\033[0m"
-  printf "\t This script is used to simulate network conditions of systems on the edge. Such as: \n" 
+  printf "\t This script is used to simulate network conditions of systems on the edge. Such as: \n"
   printf "\t\t %b Adding a delay on a specific link between nodes that increases at some rate %b to simulate a node getting further away\n" "\033[1m""-""\033[0m" "\033[1m""r""\033[0m"
   printf "\t\t %b Decreasing bandwidth to simulate constrained network conditions on the edge\n" "\033[1m""-""\033[0m"
   printf "\t\t %b Simulating a node leaving and re-joining the cluster at varying speeds\n" "\033[1m""-""\033[0m"
@@ -25,86 +25,123 @@ display_help () {
   printf "\t %b [%b], \n\t\tReset the network conditions of node %b back to normal \n\n" "\033[1m""-r""\033[0m" "\033[4m"IP"\033[0m" "\033[1m"IP"\033[0m"
   printf "\t %b,\tDisplay this help message again \n\n" "\033[1m""-h""\033[0m"
   printf "\t %b [%b] [%b] [%b],\n\t\tAdd a delay to a node up to a given max delay and with a given rate of increase per second\n" "\033[1m""-d""\033[0m" "\033[4m"IP"\033[0m" "\033[4m""MAX DELAY""\033[0m" "\033[4m"RATE"\033[0m"
-  printf "\t\tInitial delay starts at 0.1ms\n" 
+  printf "\t\tInitial delay starts at 0.1ms\n"
   printf "\n%b \n" "\033[1m"EXAMPLES"\033[0m"
   printf "\t%b\n" "\033[1m""Adding delay to a node:""\033[0m"
-  printf "\t\t./sim_net_conds -d node1 5.0 0.1\n\n" 
+  printf "\t\t./sim_net_conds -d node1 5.0 0.1\n\n"
   printf "\t%b\n" "\033[1m""Removing delay from a node:""\033[0m"
-  printf "\t\t./sim_net_conds -r node1\n\n" 
+  printf "\t\t./sim_net_conds -r node1\n\n"
   printf "\t%b\n" "\033[1m""Displaying this help message again:""\033[0m"
-  printf "\t\t./sim_net_conds -h\n\n" 
+  printf "\t\t./sim_net_conds -h\n\n"
 }
 
-continue_delay () {
-  if (( $( echo "$max_delay == -1" | bc -l ) )); then
-    return 0
-  else 
-    return $(echo "$delay >= $max_delay" | bc -l )
-  fi
-}
-
-get_ip_and_device () {
-  ## In awk FNR is the a variable that represents the number of records/lines to read
-  ip=$(ping -c 1 $1 | awk 'FNR == 1 {print $3}' | sed -e 's/^.//' -e 's/.$//')
-  ## Network interface is
-  dev=$(ip route get $ip | awk 'FNR == 1 {print $3}')
-}
-
-if (( $# < 1 )); then
+if (( $# < 4 )); then
   echo "Invalid Number of Arguments."
   echo "Use '-h' to display help."
   exit
 fi
 
+for i in "$@"; do
+    case $i in
+        ## TODO: Not sure if this will actually get a list of nodes
+        -n=*|--nodes=*)
+            NODES="${i#*=}"
+            shift # Past argument=value
+            ;;
+        ## how many time intervals of 5ms to run
+        -t=*|--time_interval=*)
+            TIMEINTERVAL="${i#*=}"
+            shift # Past argument=value
+            ;;
+        ## Increase in latency per time interval
+        -d=*|--time_delta=*)
+            TIMEDELTA="${i#*=}"
+            shift # Past argument=value
+            ;;
+        ## How many time intervals until the node starts coming back
+        -r=*|--time_return=*)
+            TIMERETURN="${i#*=}"
+            shift # Past argument=value
+            ;;
+        -*|--*)
+            echo "Unknown option $i"
+            exit 1
+            ;;
+        *)
+            ;;
+    esac
+done
 
-##
-# Reset Network changes
-##
-if [ $1 == '-r' ] ; then
+echo $NODES
+echo $TIMEINTERVAL
+echo $TIMEDELTA
+echo $TIMERETURN
 
-  if (( $# < 2 )); then
-    echo "Invalid Number of Arguments! The '-r' option requres 1 argument."
-    echo "See '-h' for help."
-    exit
-  fi 
-  get_ip_and_device $2
-
-  echo "Resetting Network Changes..."
-  ssh -T -o StrictHostKeyChecking=no $ip "sudo tc qdisc del dev $dev root" 2>&1
-
-##
-# Add additional delay to node
-# Note: The delay is added ontop of whatever network delay is already there
-##
-elif [ $1 == '-d' ] ; then
-  if (( $# < 4 )); then
-    echo "Invalid number of arguments! '-d' requires 3 arguments. See '-h' for help."
-  else
-    get_ip_and_device $2
-    delay=0.1
-    max_delay=$3
-    rate=$4
-
-    ##
-    # Initial delay of 0.1
-    # if MAX_DELAY is < 0 keep going indefinitely
-    # else go until delay >= MAX_DELAY
-    ##
-    echo "Current Additional Network Delay is: $delay" 
-    ssh -T -o StrictHostKeyChecking=no $ip "sudo tc qdisc add dev $dev root netem delay ${delay}ms"
-    while continue_delay
-    do
-     sleep 1
-     delay=$( echo "$delay+$rate" | bc -l )
-     echo "Current Additional Network Delay is: $delay" 
-     ssh -T -o StrictHostKeyChecking=no $ip "sudo tc qdisc change dev $dev root netem delay ${delay}ms"
-    done
-  fi
-elif [ $1 == '-h' ] ; then
-  display_help
-else
-  echo "Unknown Argument!"
-  echo "Use '-h' to display help."
-fi
+#continue_delay () {
+#  if (( $( echo "$max_delay == -1" | bc -l ) )); then
+#    return 0
+#  else
+#    return $(echo "$delay >= $max_delay" | bc -l )
+#  fi
+#}
+#
+#get_ip_and_device () {
+#  ## In awk FNR is the a variable that represents the number of records/lines to read
+#  ip=$(ping -c 1 $1 | awk 'FNR == 1 {print $3}' | sed -e 's/^.//' -e 's/.$//')
+#  ## Network interface is
+#  dev=$(ip route get $ip | awk 'FNR == 1 {print $3}')
+#}
+#
+#
+#
+###
+## Reset Network changes
+###
+#if [ $1 == '-r' ] ; then
+#
+#  if (( $# < 2 )); then
+#    echo "Invalid Number of Arguments! The '-r' option requres 1 argument."
+#    echo "See '-h' for help."
+#    exit
+#  fi
+#  get_ip_and_device $2
+#
+#  echo "Resetting Network Changes..."
+#  ssh -T -o StrictHostKeyChecking=no $ip "sudo tc qdisc del dev $dev root" 2>&1
+#
+###
+## Add additional delay to node
+## Note: The delay is added ontop of whatever network delay is already there
+###
+#elif [ $1 == '-d' ] ; then
+#  if (( $# < 4 )); then
+#    echo "Invalid number of arguments! '-d' requires 3 arguments. See '-h' for help."
+#  else
+#    get_ip_and_device $2
+#    delay=0.1
+#    max_delay=$3
+#    rate=$4
+#
+#    ##
+#    # Initial delay of 0.1
+#    # if MAX_DELAY is < 0 keep going indefinitely
+#    # else go until delay >= MAX_DELAY
+#    ##
+#    echo "Current Additional Network Delay is: $delay"
+#    ssh -T -o StrictHostKeyChecking=no $ip "sudo tc qdisc add dev $dev root netem delay ${delay}ms"
+#    while continue_delay
+#    do
+#     sleep 1
+#     delay=$( echo "$delay+$rate" | bc -l )
+#     echo "Current Additional Network Delay is: $delay"
+#     ssh -T -o StrictHostKeyChecking=no $ip "sudo tc qdisc change dev $dev root netem delay ${delay}ms"
+#    done
+#  fi
+#elif [ $1 == '-h' ] ; then
+#  display_help
+#else
+#  echo "Unknown Argument!"
+#  echo "Use '-h' to display help."
+#fi
 
 
